fix deployment error caused by potential indent issues
$sam deploy --guided
Error: Failed to parse template: while parsing a block collection
  in "<unicode string>", line 53, column 9:
            - Statement:
            ^
expected <block end>, but found '<block sequence start>'
  in "<unicode string>", line 62, column 10:
             - Statement:
             ^